language: cpp
compiler:
  - gcc
sudo: false
dist: xenial
os:
  - linux
script:
  - mkdir ./build
  - cd ./build
  - cmake ../
  - make -j2
  - ctest -V
addons:
  apt:
    packages:
    - libarchive-dev
    - libcurl4-gnutls-dev
    - libjsoncpp-dev
    - libunshield-dev
    - libzip-dev
notifications:
  email: false
