language: cpp
compiler:
  - gcc
sudo: false
dist: trusty
os:
  - linux
before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
script:
  - mkdir ./build
  - cd ./build
  - cmake ../
  - make -j2
  - ctest -V
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - libarchive-dev
    - libcurl4-gnutls-dev
    - libjsoncpp-dev
    - libunshield-dev
    - libzip-dev
notifications:
  email: false
